# Generated by Django 3.0.8 on 2020-12-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
                ('c_age', models.CharField(max_length=3)),
                ('c_phone', models.CharField(max_length=20)),
                ('c_fdate', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('m_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=20)),
                ('m_date', models.TextField(max_length=10)),
                ('m_price', models.DecimalField(decimal_places=1, max_digits=8)),
                ('m_inventory', models.DecimalField(decimal_places=0, max_digits=8)),
                ('m_cost', models.DecimalField(decimal_places=1, max_digits=8)),
                ('m_estdemand', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20)),
                ('p_cost', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p_price', models.DecimalField(decimal_places=1, max_digits=8)),
                ('p_inventory', models.DecimalField(decimal_places=0, max_digits=8)),
                ('p_estdemand', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_quantity', models.DecimalField(decimal_places=0, max_digits=8)),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniqlo.Material')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniqlo.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('o_price', models.DecimalField(decimal_places=1, max_digits=8)),
                ('o_date', models.TextField(max_length=10)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniqlo.Customer')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniqlo.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_quantity', models.DecimalField(decimal_places=0, max_digits=8)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniqlo.Order')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniqlo.Product')),
            ],
        ),
    ]
