# Generated by Django 3.0.8 on 2020-12-26 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_fdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='material',
            name='m_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
