# Generated by Django 3.0.8 on 2020-12-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0003_cate_profit_eoq_epq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='m_cost',
            new_name='m_hcost',
        ),
        migrations.AddField(
            model_name='material',
            name='m_estsupply',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='p_estsupply',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='p_hcost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
