# Generated by Django 3.0.8 on 2020-12-27 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0004_auto_20201227_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EOQ',
        ),
        migrations.DeleteModel(
            name='EPQ',
        ),
        migrations.AddField(
            model_name='cate_profit',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
