# Generated by Django 3.0.8 on 2020-12-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0006_cate_profit_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cate_profit',
            name='Category_Profit',
            field=models.DecimalField(decimal_places=2, default='001', max_digits=5),
        ),
    ]
