# Generated by Django 3.0.8 on 2020-12-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0007_auto_20201227_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cate_profit',
            name='Category_Profit',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cate_profit',
            name='p_id',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='uniqlo.Product'),
        ),
    ]
