# Generated by Django 3.0.8 on 2020-12-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0008_auto_20201227_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cate_profit',
            name='p_id',
        ),
    ]
