# Generated by Django 3.0.8 on 2020-12-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0009_remove_cate_profit_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='m_estdemand',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='material',
            name='m_hcost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
