# Generated by Django 3.0.8 on 2020-12-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0010_auto_20201227_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cate_Profit',
        ),
    ]
