# Generated by Django 3.0.8 on 2020-12-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0011_delete_cate_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='m_date',
        ),
        migrations.AlterField(
            model_name='material',
            name='m_estsupply',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
