# Generated by Django 3.0.8 on 2020-12-27 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0012_auto_20201227_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='m_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
