# Generated by Django 3.0.8 on 2020-12-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0014_order_o_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_profit',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
