# Generated by Django 3.0.8 on 2021-01-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0015_order_o_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Retention', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Survival', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Active_Customers', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Active_Periods', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='o_profit',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_quantity',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=8),
        ),
    ]
