# Generated by Django 3.0.8 on 2021-01-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0016_auto_20210101_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retention',
            name='id',
        ),
        migrations.AlterField(
            model_name='retention',
            name='Period',
            field=models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False),
        ),
    ]
