# Generated by Django 3.0.8 on 2021-01-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqlo', '0017_auto_20210101_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='m_reorder',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='p_reorder',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=8),
        ),
    ]
